# Conexão com banco de dados
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=123456
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/Pizzaria

# Habilitar criação automática do banco (apenas para dev)
quarkus.hibernate-orm.database.generation=drop-and-create

# Mostrar SQL no terminal
quarkus.hibernate-orm.log.sql=true

# Configuração de charset para evitar problemas com acentos
quarkus.http.encoding.charset=UTF-8
quarkus.http.encoding.enabled=true

# Desativar os Dev Services
quarkus.devservices.enabled=false
quarkus.container-image.build=false
quarkus.container-image.push=false

# Diretório das imagens
pizzaria.upload.dir=/opt/pizzaria/uploads/pizzas

# Caminho para a chave pública (validação)
mp.jwt.verify.publickey.location=publicKey.pem

# Caminho para a chave privada (assinatura)
smallrye.jwt.sign.key.location=privateKey.pem

# Algoritmo
mp.jwt.verify.algorithm=RS256

# Emissor (tem que bater com o que você usa no .issuer())
mp.jwt.verify.issuer=https://pizzaria-api

# Tempo de expiração
smallrye.jwt.new-token.lifespan=7200

# Permite GET público para /ingredientes
quarkus.http.auth.permission.public-ingredientes.paths=/ingredientes
quarkus.http.auth.permission.public-ingredientes.policy=permit
quarkus.http.auth.permission.public-ingredientes.methods=GET

# Protege POST, PUT e DELETE em /ingredientes (sem barra no final)
quarkus.http.auth.permission.authenticated-ingredientes.paths=/ingredientes
quarkus.http.auth.permission.authenticated-ingredientes.policy=authenticated
quarkus.http.auth.permission.authenticated-ingredientes.methods=POST,PUT,DELETE


# Permite GET público
quarkus.http.auth.permission.public-pizzas.paths=/pizzas
quarkus.http.auth.permission.public-pizzas.policy=permit
quarkus.http.auth.permission.public-pizzas.methods=GET

# Protege POST, PUT e DELETE em /pizzas (sem barra no final)
quarkus.http.auth.permission.authenticated-pizzas.paths=/pizzas
quarkus.http.auth.permission.authenticated-pizzas.policy=authenticated
quarkus.http.auth.permission.authenticated-pizzas.methods=POST,PUT,DELETE

# habilita CORS
quarkus.http.cors=true

# de onde você permite chamadas (o front)
quarkus.http.cors.origins=http://localhost:3000

# métodos e headers usados pelo seu front
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

# (opcional) headers que o browser pode ler na resposta
quarkus.http.cors.exposed-headers=Authorization,Content-Disposition

# (opcional) se for usar cookies/credentials no fetch
# ATENÇÃO: se true, NÃO pode usar origins="*"
quarkus.http.cors.access-control-allow-credentials=true
